/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Params = t.iface([], {
  "host": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  Params,
};
export default exportedTypeSuite;
