import * as c from "tennyson/lib/core/common";

import * as yaml from "yaml";

function makeMatch(replace: string, triggers: string | string[]) {
  return {
    replace,
    triggers: c.toArray(triggers).map((x) => `;${x};`),
  };
}

const m = makeMatch;

const matches = () => [
  // emoji ////////////////////////////////////////////////////////////////////
  m("🌸", ["flower"]),
  m("😘", ["kiss"]),
  m("🥵", ["gasp"]),
  m("😇", ["angel"]),
  m("🥹", ["aww"]),
  m("❤️", ["heart", "<3"]),

  m("ℹ️", ["info"]),
  m("⚠️", ["warn"]),
  m("🛑️", ["stop"]),
  m("✅", ["check"]),
  m("⭐", ["star"]),
  m("❓", ["?"]),
  m("🚨", ["alarm"]),
  m("🔥", ["fire"]),

  m("🐈‍⬛", ["cat"]),
  m("🐶", ["dog"]),

  m("✉️", ["mail"]),
  m("🎵", ["music"]),
  m("🏃", ["run"]),
  m("📞", ["phone"]),
  m("📁", ["file"]),
  m("🤖️", ["robot"]),
  m("🔒", ["lock"]),
  m("💪️", ["flex", "strong"]),
  m("🗽", ["nyc"]),
  m("✈️", ["airplane", "plane"]),
  m("🚕", ["taxi"]),
  m("🚗", ["car"]),
  m("🌮", ["taco"]),
  m("💼", ["briefcase"]),

  m("📈️", ["bull", "stock"]),
  m("📉", ["bust"]),
  m("💻", ["laptop"]),
  m("🛠️", ["tools"]),
  m("🔄", ["sync"]),
  m("🧵", ["thread"]),

  m("⚪", ["white"]),
  m("⚫", ["black"]),
  m("🔴", ["red"]),
  m("🔵", ["blue"]),
  m("🟠", ["orange"]),
  m("🟡", ["yellow"]),
  m("🟢", ["green"]),
  m("🟣", ["purple"]),
  m("🟤", ["brown"]),

  m("➡️", ["right", "->"]),
  m("⬅️", ["left", "<-"]),
  m("⬆️", ["up"]),
  m("⬇️", ["down"]),

  m("¢", ["cent"]),
  m("€", ["euro"]),
  m("₤", ["gbp"]),
  m("₿", ["bitcoin"]),
  m("¥", ["yen", "yuan"]),

  // math /////////////////////////////////////////////////////////////////////
  m("∀", ["forall"]),
  m("∈", ["in"]),
  m("∃", ["exists"]),
  m("∪", ["cup"]),
  m("∩", ["cap"]),
  m("⊆", ["subseteq"]),

  m("≤", ["leq"]),
  m("≥", ["geq"]),
  m("≈", ["approx"]),

  m("∇", ["nabla"]),
  m("∞", ["infty"]),
  m("∫", ["int"]),
  m("√", ["sqrt"]),

  m("⨁ ", ["oplus"]),
  m("⨂ ", ["otimes"]),
  m("×", ["times"]),
  m("⋅", ["cdot"]),
  m("∑", ["Sigma"]),
  m("∏", ["Pi"]),

  ...c
    .zip(
      [
        ...c.AlphaNumeric.alphaMathBlackboardUpperCase,
        ...c.AlphaNumeric.numericMathBlackboard,
      ],
      [...c.AlphaNumeric.alphaLower, ...c.AlphaNumeric.numeric],
    )
    .map(([u, c]: [string, string]) => m(u, `bb ${c.toUpperCase()}`)),

  ...c
    .zip(
      [...c.AlphaNumeric.alphaMathBlackboardLowerCase],
      c.AlphaNumeric.alphaLower,
    )
    .map(([u, c]: [string, string]) => m(u, `bb ${c}`)),

  ...c
    .zip([...c.AlphaNumeric.alphaMathCal], c.AlphaNumeric.alphaLower)
    .map(([u, c]: [string, string]) => m(u, `cal ${c.toUpperCase()}`)),

  // greek
  m("β", ["beta"]),
  m("δ", ["delta"]),
  m("ε", ["epsilon"]),
  m("λ", ["lambda"]),
  m("μ", ["mu"]),
  m("π", ["pi"]),
  m("σ", ["sigma"]),
  m("∂", ["partial"]),
];

export function gen() {
  return "# autogenerated file\n\n" + yaml.stringify({ matches: matches() });
}
